### ISSUE TITLE
fatal error: shox96_0_2.h: No such file or directory

### ISSUE THREAD

**Issue by scottchiefbaker** [siara-cc/Shox96_Arduino_Progmem_lib#1]
I've cloned this repo in to `~/Arduino/libraries` and now it shows in the Arduino IDE correctly. When I attempt to compile any of the examples I get:

    /home/bakers/Arduino/libraries/Shox96_Arduino_Progmem_lib/src/shox96_progmem_0_2.cpp:28:24: fatal error: shox96_0_2.h: No such file or directory
    compilation terminated.
    Using library Shox96_Arduino_Progmem_lib at version 1.0 in folder: /home/bakers/Arduino/libraries/Shox96_Arduino_Progmem_lib 
    exit status 1
    Error compiling for board Arduino/Genuino Uno.

I'm assuming I also need to install the core `shox96` library somewhere so this will pick it up? Nothing is mentioned in the documentation so I'm not sure the correct install procedure.

**Comment by siara-cc** [comment]
Thank you for pointing it out.  It was my mistake.  It is just a standard Arduino library.  No additional procedures needed.  Please download again and compile.

**Comment by scottchiefbaker** [comment]
That corrected my issue thank you!
